### ISSUE TITLE
Running exps with Dreamer-V3

### ISSUE THREAD

**Issue by belerico** [PWhiddy/PokemonRedExperiments#147]
Hi guys, first of all what an awesome video you've done on YT!
I'm one of the maintainers of [sheeprl](https://github.com/Eclectic-Sheep/sheeprl) and I'm here just to tell you that we're running experiments with Dreamer-V3 on the standard env. 
Right now I have modified your env code inside sheeprl and in the future we want to try out also the v2.
This is what I'm getting right now in terms of rewards:

![image](https://github.com/PWhiddy/PokemonRedExperiments/assets/18405289/10312013-62bd-496c-b702-47ba894c61ab)

This is the configuration I'm using:

```yaml
headless: True
    save_final_state: True
    early_stop: False
    action_freq: 24
    max_steps: 20480
    print_rewards: True
    save_video: False
    fast_video: True
    debug: False
    sim_frame_dist: 2_000_000.0
    use_screen_explore: True
    reward_scale: 4
    extra_buttons: False
    explore_weight: 3 # 2.5
```

I don't know if those are good results, but I wanted to share them. 
If you wanna try out something with SheepRL let us now :sheep:.
Thank you again!
